"""add original_url to links

Revision ID: 52c28ccec1ed
Revises: 6f3aa79e0743
Create Date: 2026-03-09 14:38:27.280301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c28ccec1ed'
down_revision: Union[str, None] = '6f3aa79e0743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('original_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'original_url')
    # ### end Alembic commands ###
